// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TenureSchema
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public partial class Notices : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse(@"{""type"":""record"",""name"":""Notices"",""namespace"":""TenureSchema"",""fields"":[{""name"":""Type"",""type"":""string""},{""name"":""ServedDate"",""type"":""int"",""logicalType"":""date""},{""name"":""ExpiryDate"",""type"":""int"",""logicalType"":""date""},{""name"":""EffectiveDate"",""type"":""int"",""logicalType"":""date""},{""name"":""EndDate"",""type"":""int"",""logicalType"":""date""}]}");
		private string _Type;
		private int _ServedDate;
		private int _ExpiryDate;
		private int _EffectiveDate;
		private int _EndDate;
		public virtual Schema Schema
		{
			get
			{
				return Notices._SCHEMA;
			}
		}
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				this._Type = value;
			}
		}
		public int ServedDate
		{
			get
			{
				return this._ServedDate;
			}
			set
			{
				this._ServedDate = value;
			}
		}
		public int ExpiryDate
		{
			get
			{
				return this._ExpiryDate;
			}
			set
			{
				this._ExpiryDate = value;
			}
		}
		public int EffectiveDate
		{
			get
			{
				return this._EffectiveDate;
			}
			set
			{
				this._EffectiveDate = value;
			}
		}
		public int EndDate
		{
			get
			{
				return this._EndDate;
			}
			set
			{
				this._EndDate = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.Type;
			case 1: return this.ServedDate;
			case 2: return this.ExpiryDate;
			case 3: return this.EffectiveDate;
			case 4: return this.EndDate;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.Type = (System.String)fieldValue; break;
			case 1: this.ServedDate = (System.Int32)fieldValue; break;
			case 2: this.ExpiryDate = (System.Int32)fieldValue; break;
			case 3: this.EffectiveDate = (System.Int32)fieldValue; break;
			case 4: this.EndDate = (System.Int32)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
