// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TenureSchema
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public partial class TenureInformation : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse("{\"type\":\"record\",\"name\":\"TenureInformation\",\"namespace\":\"TenureSchema\",\"fields\":[" +
				"{\"name\":\"Id\",\"type\":\"string\",\"logicalType\":\"uuid\"},{\"name\":\"PaymentReference\",\"t" +
				"ype\":\"string\"},{\"name\":\"HouseholdMembers\",\"type\":{\"type\":\"array\",\"items\":{\"type\"" +
				":\"record\",\"name\":\"HouseholdMember\",\"namespace\":\"TenureSchema\",\"fields\":[{\"name\":" +
				"\"Id\",\"type\":\"string\",\"logicalType\":\"uuid\"},{\"name\":\"HouseholdMembers\",\"type\":{\"t" +
				"ype\":\"enum\",\"name\":\"HouseholdMembersType\",\"namespace\":\"TenureSchema\",\"symbols\":[" +
				"\"Person\",\"Organization\"]}},{\"name\":\"FullName\",\"type\":\"string\"},{\"name\":\"IsRespon" +
				"sible\",\"type\":\"boolean\"},{\"name\":\"DateOfBirth\",\"type\":\"int\",\"logicalType\":\"date\"" +
				"},{\"name\":\"PersonTenure\",\"type\":{\"type\":\"enum\",\"name\":\"PersonTenureType\",\"namesp" +
				"ace\":\"TenureSchema\",\"symbols\":[\"Tenant\",\"Leaseholder\",\"Freeholder\",\"HouseholdMem" +
				"ber\",\"Occupant\"]}}]}}},{\"name\":\"TenuredAsset\",\"type\":{\"type\":\"record\",\"name\":\"Te" +
				"nuredAsset\",\"namespace\":\"TenureSchema\",\"fields\":[{\"name\":\"Id\",\"type\":\"string\",\"l" +
				"ogicalType\":\"uuid\"},{\"name\":\"TenuredAsset\",\"type\":{\"type\":\"enum\",\"name\":\"Tenured" +
				"AssetType\",\"namespace\":\"TenureSchema\",\"symbols\":[\"Block\",\"Concierge\",\"Dwelling\"," +
				"\"LettableNonDwelling\",\"MediumRiseBlock\",\"NA\",\"TravellerSite\"]}},{\"name\":\"FullAdd" +
				"ress\",\"type\":\"string\"},{\"name\":\"Uprn\",\"type\":\"string\"},{\"name\":\"PropertyReferenc" +
				"e\",\"type\":\"string\"}]}},{\"name\":\"Charges\",\"type\":{\"type\":\"record\",\"name\":\"Charges" +
				"\",\"namespace\":\"TenureSchema\",\"fields\":[{\"name\":\"Rent\",\"type\":\"float\"},{\"name\":\"C" +
				"urrentBalance\",\"type\":\"float\"},{\"name\":\"BillingFrequency\",\"type\":\"string\"},{\"nam" +
				"e\":\"ServiceCharge\",\"type\":\"float\"},{\"name\":\"OtherCharges\",\"type\":\"float\"},{\"name" +
				"\":\"CombinedServiceCharges\",\"type\":\"float\"},{\"name\":\"CombinedRentCharges\",\"type\":" +
				"\"float\"},{\"name\":\"TenancyInsuranceCharge\",\"type\":\"float\"},{\"name\":\"OriginalRentC" +
				"harge\",\"type\":\"float\"},{\"name\":\"OriginalServiceCharge\",\"type\":\"float\"}]}},{\"name" +
				"\":\"StartOfTenureDate\",\"type\":\"int\",\"logicalType\":\"date\"},{\"name\":\"EndOfTenureDat" +
				"e\",\"type\":\"int\",\"logicalType\":\"date\"},{\"name\":\"TenureType\",\"type\":{\"type\":\"recor" +
				"d\",\"name\":\"TenureType\",\"namespace\":\"TenureSchema\",\"fields\":[{\"name\":\"Rent\",\"type" +
				"\":\"float\"},{\"name\":\"CurrentBalance\",\"type\":\"float\"},{\"name\":\"BillingFrequency\",\"" +
				"type\":\"string\"},{\"name\":\"ServiceCharge\",\"type\":\"float\"},{\"name\":\"OtherCharges\",\"" +
				"type\":\"float\"},{\"name\":\"CombinedServiceCharges\",\"type\":\"float\"},{\"name\":\"Combine" +
				"dRentCharges\",\"type\":\"float\"},{\"name\":\"TenancyInsuranceCharge\",\"type\":\"float\"},{" +
				"\"name\":\"OriginalRentCharge\",\"type\":\"float\"},{\"name\":\"OriginalServiceCharge\",\"typ" +
				"e\":\"float\"}]}},{\"name\":\"IsTenanted\",\"type\":\"boolean\"},{\"name\":\"Terminated\",\"type" +
				"\":{\"type\":\"record\",\"name\":\"Terminated\",\"namespace\":\"TenureSchema\",\"fields\":[{\"na" +
				"me\":\"IsTerminated\",\"type\":\"boolean\"},{\"name\":\"ReasonForTermination\",\"type\":\"stri" +
				"ng\"}]}},{\"name\":\"SuccessionDate\",\"type\":\"int\",\"logicalType\":\"date\"},{\"name\":\"Agr" +
				"eementType\",\"type\":{\"type\":\"record\",\"name\":\"AgreementType\",\"namespace\":\"TenureSc" +
				"hema\",\"fields\":[{\"name\":\"Code\",\"type\":\"string\"},{\"name\":\"Description\",\"type\":\"st" +
				"ring\"}]}},{\"name\":\"EvictionDate\",\"type\":\"int\",\"logicalType\":\"date\"},{\"name\":\"Pot" +
				"entialEndDate\",\"type\":\"int\",\"logicalType\":\"date\"},{\"name\":\"Notices\",\"type\":{\"typ" +
				"e\":\"record\",\"name\":\"Notices\",\"namespace\":\"TenureSchema\",\"fields\":[{\"name\":\"Type\"" +
				",\"type\":\"string\"},{\"name\":\"ServedDate\",\"type\":\"int\",\"logicalType\":\"date\"},{\"name" +
				"\":\"ExpiryDate\",\"type\":\"int\",\"logicalType\":\"date\"},{\"name\":\"EffectiveDate\",\"type\"" +
				":\"int\",\"logicalType\":\"date\"},{\"name\":\"EndDate\",\"type\":\"int\",\"logicalType\":\"date\"" +
				"}]}},{\"name\":\"LegacyReferences\",\"type\":{\"type\":\"record\",\"name\":\"LegacyReferences" +
				"\",\"namespace\":\"TenureSchema\",\"fields\":[{\"name\":\"Name\",\"type\":\"string\"},{\"name\":\"" +
				"Value\",\"type\":\"string\"}]}},{\"name\":\"IsMutualExchange\",\"type\":\"boolean\"},{\"name\":" +
				"\"InformHousingBenefitsForChanges\",\"type\":\"boolean\"},{\"name\":\"IsSublet\",\"type\":\"b" +
				"oolean\"},{\"name\":\"SubletEndDate\",\"type\":\"int\",\"logicalType\":\"date\"},{\"name\":\"Ver" +
				"sionNumber\",\"type\":\"int\"}]}");
		private string _Id;
		private string _PaymentReference;
		private IList<TenureSchema.HouseholdMember> _HouseholdMembers;
		private TenureSchema.TenuredAsset _TenuredAsset;
		private TenureSchema.Charges _Charges;
		private int _StartOfTenureDate;
		private int _EndOfTenureDate;
		private TenureSchema.TenureType _TenureType;
		private bool _IsTenanted;
		private TenureSchema.Terminated _Terminated;
		private int _SuccessionDate;
		private TenureSchema.AgreementType _AgreementType;
		private int _EvictionDate;
		private int _PotentialEndDate;
		private TenureSchema.Notices _Notices;
		private TenureSchema.LegacyReferences _LegacyReferences;
		private bool _IsMutualExchange;
		private bool _InformHousingBenefitsForChanges;
		private bool _IsSublet;
		private int _SubletEndDate;
		private int _VersionNumber;
		public virtual Schema Schema
		{
			get
			{
				return TenureInformation._SCHEMA;
			}
		}
		public string Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				this._Id = value;
			}
		}
		public string PaymentReference
		{
			get
			{
				return this._PaymentReference;
			}
			set
			{
				this._PaymentReference = value;
			}
		}
		public IList<TenureSchema.HouseholdMember> HouseholdMembers
		{
			get
			{
				return this._HouseholdMembers;
			}
			set
			{
				this._HouseholdMembers = value;
			}
		}
		public TenureSchema.TenuredAsset TenuredAsset
		{
			get
			{
				return this._TenuredAsset;
			}
			set
			{
				this._TenuredAsset = value;
			}
		}
		public TenureSchema.Charges Charges
		{
			get
			{
				return this._Charges;
			}
			set
			{
				this._Charges = value;
			}
		}
		public int StartOfTenureDate
		{
			get
			{
				return this._StartOfTenureDate;
			}
			set
			{
				this._StartOfTenureDate = value;
			}
		}
		public int EndOfTenureDate
		{
			get
			{
				return this._EndOfTenureDate;
			}
			set
			{
				this._EndOfTenureDate = value;
			}
		}
		public TenureSchema.TenureType TenureType
		{
			get
			{
				return this._TenureType;
			}
			set
			{
				this._TenureType = value;
			}
		}
		public bool IsTenanted
		{
			get
			{
				return this._IsTenanted;
			}
			set
			{
				this._IsTenanted = value;
			}
		}
		public TenureSchema.Terminated Terminated
		{
			get
			{
				return this._Terminated;
			}
			set
			{
				this._Terminated = value;
			}
		}
		public int SuccessionDate
		{
			get
			{
				return this._SuccessionDate;
			}
			set
			{
				this._SuccessionDate = value;
			}
		}
		public TenureSchema.AgreementType AgreementType
		{
			get
			{
				return this._AgreementType;
			}
			set
			{
				this._AgreementType = value;
			}
		}
		public int EvictionDate
		{
			get
			{
				return this._EvictionDate;
			}
			set
			{
				this._EvictionDate = value;
			}
		}
		public int PotentialEndDate
		{
			get
			{
				return this._PotentialEndDate;
			}
			set
			{
				this._PotentialEndDate = value;
			}
		}
		public TenureSchema.Notices Notices
		{
			get
			{
				return this._Notices;
			}
			set
			{
				this._Notices = value;
			}
		}
		public TenureSchema.LegacyReferences LegacyReferences
		{
			get
			{
				return this._LegacyReferences;
			}
			set
			{
				this._LegacyReferences = value;
			}
		}
		public bool IsMutualExchange
		{
			get
			{
				return this._IsMutualExchange;
			}
			set
			{
				this._IsMutualExchange = value;
			}
		}
		public bool InformHousingBenefitsForChanges
		{
			get
			{
				return this._InformHousingBenefitsForChanges;
			}
			set
			{
				this._InformHousingBenefitsForChanges = value;
			}
		}
		public bool IsSublet
		{
			get
			{
				return this._IsSublet;
			}
			set
			{
				this._IsSublet = value;
			}
		}
		public int SubletEndDate
		{
			get
			{
				return this._SubletEndDate;
			}
			set
			{
				this._SubletEndDate = value;
			}
		}
		public int VersionNumber
		{
			get
			{
				return this._VersionNumber;
			}
			set
			{
				this._VersionNumber = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.Id;
			case 1: return this.PaymentReference;
			case 2: return this.HouseholdMembers;
			case 3: return this.TenuredAsset;
			case 4: return this.Charges;
			case 5: return this.StartOfTenureDate;
			case 6: return this.EndOfTenureDate;
			case 7: return this.TenureType;
			case 8: return this.IsTenanted;
			case 9: return this.Terminated;
			case 10: return this.SuccessionDate;
			case 11: return this.AgreementType;
			case 12: return this.EvictionDate;
			case 13: return this.PotentialEndDate;
			case 14: return this.Notices;
			case 15: return this.LegacyReferences;
			case 16: return this.IsMutualExchange;
			case 17: return this.InformHousingBenefitsForChanges;
			case 18: return this.IsSublet;
			case 19: return this.SubletEndDate;
			case 20: return this.VersionNumber;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.Id = (System.String)fieldValue; break;
			case 1: this.PaymentReference = (System.String)fieldValue; break;
			case 2: this.HouseholdMembers = (IList<TenureSchema.HouseholdMember>)fieldValue; break;
			case 3: this.TenuredAsset = (TenureSchema.TenuredAsset)fieldValue; break;
			case 4: this.Charges = (TenureSchema.Charges)fieldValue; break;
			case 5: this.StartOfTenureDate = (System.Int32)fieldValue; break;
			case 6: this.EndOfTenureDate = (System.Int32)fieldValue; break;
			case 7: this.TenureType = (TenureSchema.TenureType)fieldValue; break;
			case 8: this.IsTenanted = (System.Boolean)fieldValue; break;
			case 9: this.Terminated = (TenureSchema.Terminated)fieldValue; break;
			case 10: this.SuccessionDate = (System.Int32)fieldValue; break;
			case 11: this.AgreementType = (TenureSchema.AgreementType)fieldValue; break;
			case 12: this.EvictionDate = (System.Int32)fieldValue; break;
			case 13: this.PotentialEndDate = (System.Int32)fieldValue; break;
			case 14: this.Notices = (TenureSchema.Notices)fieldValue; break;
			case 15: this.LegacyReferences = (TenureSchema.LegacyReferences)fieldValue; break;
			case 16: this.IsMutualExchange = (System.Boolean)fieldValue; break;
			case 17: this.InformHousingBenefitsForChanges = (System.Boolean)fieldValue; break;
			case 18: this.IsSublet = (System.Boolean)fieldValue; break;
			case 19: this.SubletEndDate = (System.Int32)fieldValue; break;
			case 20: this.VersionNumber = (System.Int32)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
