// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TenureSchema
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public partial class Terminated : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse("{\"type\":\"record\",\"name\":\"Terminated\",\"namespace\":\"TenureSchema\",\"fields\":[{\"name\"" +
				":\"IsTerminated\",\"type\":\"boolean\"},{\"name\":\"ReasonForTermination\",\"type\":\"string\"" +
				"}]}");
		private bool _IsTerminated;
		private string _ReasonForTermination;
		public virtual Schema Schema
		{
			get
			{
				return Terminated._SCHEMA;
			}
		}
		public bool IsTerminated
		{
			get
			{
				return this._IsTerminated;
			}
			set
			{
				this._IsTerminated = value;
			}
		}
		public string ReasonForTermination
		{
			get
			{
				return this._ReasonForTermination;
			}
			set
			{
				this._ReasonForTermination = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.IsTerminated;
			case 1: return this.ReasonForTermination;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.IsTerminated = (System.Boolean)fieldValue; break;
			case 1: this.ReasonForTermination = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
