// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MMH
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public partial class Charges : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse(@"{""type"":""record"",""name"":""Charges"",""namespace"":""MMH"",""fields"":[{""name"":""Rent"",""type"":""float""},{""name"":""CurrentBalance"",""type"":""float""},{""name"":""BillingFrequency"",""type"":""string""},{""name"":""ServiceCharge"",""type"":""float""},{""name"":""OtherCharges"",""type"":""float""},{""name"":""CombinedServiceCharges"",""type"":""float""},{""name"":""CombinedRentCharges"",""type"":""float""},{""name"":""TenancyInsuranceCharge"",""type"":""float""},{""name"":""OriginalRentCharge"",""type"":""float""},{""name"":""OriginalServiceCharge"",""type"":""float""}]}");
		private float _Rent;
		private float _CurrentBalance;
		private string _BillingFrequency;
		private float _ServiceCharge;
		private float _OtherCharges;
		private float _CombinedServiceCharges;
		private float _CombinedRentCharges;
		private float _TenancyInsuranceCharge;
		private float _OriginalRentCharge;
		private float _OriginalServiceCharge;
		public virtual Schema Schema
		{
			get
			{
				return Charges._SCHEMA;
			}
		}
		public float Rent
		{
			get
			{
				return this._Rent;
			}
			set
			{
				this._Rent = value;
			}
		}
		public float CurrentBalance
		{
			get
			{
				return this._CurrentBalance;
			}
			set
			{
				this._CurrentBalance = value;
			}
		}
		public string BillingFrequency
		{
			get
			{
				return this._BillingFrequency;
			}
			set
			{
				this._BillingFrequency = value;
			}
		}
		public float ServiceCharge
		{
			get
			{
				return this._ServiceCharge;
			}
			set
			{
				this._ServiceCharge = value;
			}
		}
		public float OtherCharges
		{
			get
			{
				return this._OtherCharges;
			}
			set
			{
				this._OtherCharges = value;
			}
		}
		public float CombinedServiceCharges
		{
			get
			{
				return this._CombinedServiceCharges;
			}
			set
			{
				this._CombinedServiceCharges = value;
			}
		}
		public float CombinedRentCharges
		{
			get
			{
				return this._CombinedRentCharges;
			}
			set
			{
				this._CombinedRentCharges = value;
			}
		}
		public float TenancyInsuranceCharge
		{
			get
			{
				return this._TenancyInsuranceCharge;
			}
			set
			{
				this._TenancyInsuranceCharge = value;
			}
		}
		public float OriginalRentCharge
		{
			get
			{
				return this._OriginalRentCharge;
			}
			set
			{
				this._OriginalRentCharge = value;
			}
		}
		public float OriginalServiceCharge
		{
			get
			{
				return this._OriginalServiceCharge;
			}
			set
			{
				this._OriginalServiceCharge = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.Rent;
			case 1: return this.CurrentBalance;
			case 2: return this.BillingFrequency;
			case 3: return this.ServiceCharge;
			case 4: return this.OtherCharges;
			case 5: return this.CombinedServiceCharges;
			case 6: return this.CombinedRentCharges;
			case 7: return this.TenancyInsuranceCharge;
			case 8: return this.OriginalRentCharge;
			case 9: return this.OriginalServiceCharge;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.Rent = (System.Single)fieldValue; break;
			case 1: this.CurrentBalance = (System.Single)fieldValue; break;
			case 2: this.BillingFrequency = (System.String)fieldValue; break;
			case 3: this.ServiceCharge = (System.Single)fieldValue; break;
			case 4: this.OtherCharges = (System.Single)fieldValue; break;
			case 5: this.CombinedServiceCharges = (System.Single)fieldValue; break;
			case 6: this.CombinedRentCharges = (System.Single)fieldValue; break;
			case 7: this.TenancyInsuranceCharge = (System.Single)fieldValue; break;
			case 8: this.OriginalRentCharge = (System.Single)fieldValue; break;
			case 9: this.OriginalServiceCharge = (System.Single)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
