// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MMH
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public partial class HouseholdMember : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse(@"{""type"":""record"",""name"":""HouseholdMember"",""namespace"":""MMH"",""fields"":[{""name"":""Id"",""type"":""string"",""logicalType"":""uuid""},{""name"":""HouseholdMembersType"",""type"":{""type"":""enum"",""name"":""HouseholdMembersType"",""namespace"":""MMH"",""symbols"":[""Person"",""Organization""]}},{""name"":""FullName"",""type"":""string""},{""name"":""IsResponsible"",""type"":""boolean""},{""name"":""DateOfBirth"",""type"":""int"",""logicalType"":""date""},{""name"":""PersonTenureType"",""type"":{""type"":""enum"",""name"":""PersonTenureType"",""namespace"":""MMH"",""symbols"":[""Tenant"",""Leaseholder"",""Freeholder"",""HouseholdMember"",""Occupant""]}}]}");
		private string _Id;
		private MMH.HouseholdMembersType _HouseholdMembersType;
		private string _FullName;
		private bool _IsResponsible;
		private int _DateOfBirth;
		private MMH.PersonTenureType _PersonTenureType;
		public virtual Schema Schema
		{
			get
			{
				return HouseholdMember._SCHEMA;
			}
		}
		public string Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				this._Id = value;
			}
		}
		public MMH.HouseholdMembersType HouseholdMembersType
		{
			get
			{
				return this._HouseholdMembersType;
			}
			set
			{
				this._HouseholdMembersType = value;
			}
		}
		public string FullName
		{
			get
			{
				return this._FullName;
			}
			set
			{
				this._FullName = value;
			}
		}
		public bool IsResponsible
		{
			get
			{
				return this._IsResponsible;
			}
			set
			{
				this._IsResponsible = value;
			}
		}
		public int DateOfBirth
		{
			get
			{
				return this._DateOfBirth;
			}
			set
			{
				this._DateOfBirth = value;
			}
		}
		public MMH.PersonTenureType PersonTenureType
		{
			get
			{
				return this._PersonTenureType;
			}
			set
			{
				this._PersonTenureType = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.Id;
			case 1: return this.HouseholdMembersType;
			case 2: return this.FullName;
			case 3: return this.IsResponsible;
			case 4: return this.DateOfBirth;
			case 5: return this.PersonTenureType;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.Id = (System.String)fieldValue; break;
			case 1: this.HouseholdMembersType = (MMH.HouseholdMembersType)fieldValue; break;
			case 2: this.FullName = (System.String)fieldValue; break;
			case 3: this.IsResponsible = (System.Boolean)fieldValue; break;
			case 4: this.DateOfBirth = (System.Int32)fieldValue; break;
			case 5: this.PersonTenureType = (MMH.PersonTenureType)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
