// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MMH
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public partial class TenureInformation : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse("{\"type\":\"record\",\"name\":\"TenureInformation\",\"namespace\":\"MMH\",\"fields\":[{\"name\":\"" +
				"Id\",\"type\":\"string\",\"logicalType\":\"uuid\"},{\"name\":\"PaymentReference\",\"type\":\"str" +
				"ing\"},{\"name\":\"HouseholdMembers\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\"" +
				",\"name\":\"HouseholdMember\",\"namespace\":\"MMH\",\"fields\":[{\"name\":\"Id\",\"type\":\"strin" +
				"g\",\"logicalType\":\"uuid\"},{\"name\":\"HouseholdMembersType\",\"type\":{\"type\":\"enum\",\"n" +
				"ame\":\"HouseholdMembersType\",\"namespace\":\"MMH\",\"symbols\":[\"Person\",\"Organization\"" +
				"]}},{\"name\":\"FullName\",\"type\":\"string\"},{\"name\":\"IsResponsible\",\"type\":\"boolean\"" +
				"},{\"name\":\"DateOfBirth\",\"type\":\"int\",\"logicalType\":\"date\"},{\"name\":\"PersonTenure" +
				"Type\",\"type\":{\"type\":\"enum\",\"name\":\"PersonTenureType\",\"namespace\":\"MMH\",\"symbols" +
				"\":[\"Tenant\",\"Leaseholder\",\"Freeholder\",\"HouseholdMember\",\"Occupant\"]}}]}}},{\"nam" +
				"e\":\"TenuredAsset\",\"type\":{\"type\":\"record\",\"name\":\"TenuredAsset\",\"namespace\":\"MMH" +
				"\",\"fields\":[{\"name\":\"Id\",\"type\":\"string\",\"logicalType\":\"uuid\"},{\"name\":\"TenuredA" +
				"ssetType\",\"type\":[{\"type\":\"enum\",\"name\":\"TenuredAssetType\",\"namespace\":\"MMH\",\"sy" +
				"mbols\":[\"Block\",\"Concierge\",\"Dwelling\",\"LettableNonDwelling\",\"MediumRiseBlock\",\"" +
				"NA\",\"TravellerSite\"]},\"null\"]},{\"name\":\"FullAddress\",\"type\":\"string\"},{\"name\":\"U" +
				"prn\",\"type\":\"string\"},{\"name\":\"PropertyReference\",\"type\":\"string\"}]}},{\"name\":\"C" +
				"harges\",\"type\":{\"type\":\"record\",\"name\":\"Charges\",\"namespace\":\"MMH\",\"fields\":[{\"n" +
				"ame\":\"Rent\",\"type\":\"float\"},{\"name\":\"CurrentBalance\",\"type\":\"float\"},{\"name\":\"Bi" +
				"llingFrequency\",\"type\":\"string\"},{\"name\":\"ServiceCharge\",\"type\":\"float\"},{\"name\"" +
				":\"OtherCharges\",\"type\":\"float\"},{\"name\":\"CombinedServiceCharges\",\"type\":\"float\"}" +
				",{\"name\":\"CombinedRentCharges\",\"type\":\"float\"},{\"name\":\"TenancyInsuranceCharge\"," +
				"\"type\":\"float\"},{\"name\":\"OriginalRentCharge\",\"type\":\"float\"},{\"name\":\"OriginalSe" +
				"rviceCharge\",\"type\":\"float\"}]}},{\"name\":\"StartOfTenureDate\",\"type\":[\"int\",\"null\"" +
				"],\"logicalType\":\"date\"},{\"name\":\"EndOfTenureDate\",\"type\":[\"int\",\"null\"],\"logical" +
				"Type\":\"date\"},{\"name\":\"TenureType\",\"type\":{\"type\":\"record\",\"name\":\"TenureType\",\"" +
				"namespace\":\"MMH\",\"fields\":[{\"name\":\"Code\",\"type\":\"string\"},{\"name\":\"Description\"" +
				",\"type\":\"string\"}]}},{\"name\":\"IsTenanted\",\"type\":[\"boolean\",\"null\"]},{\"name\":\"Te" +
				"rminated\",\"type\":{\"type\":\"record\",\"name\":\"Terminated\",\"namespace\":\"MMH\",\"fields\"" +
				":[{\"name\":\"IsTerminated\",\"type\":\"boolean\"},{\"name\":\"ReasonForTermination\",\"type\"" +
				":\"string\"}]}},{\"name\":\"SuccessionDate\",\"type\":[\"int\",\"null\"],\"logicalType\":\"date" +
				"\"},{\"name\":\"AgreementType\",\"type\":{\"type\":\"record\",\"name\":\"AgreementType\",\"names" +
				"pace\":\"MMH\",\"fields\":[{\"name\":\"Code\",\"type\":\"string\"},{\"name\":\"Description\",\"typ" +
				"e\":\"string\"}]}},{\"name\":\"EvictionDate\",\"type\":[\"int\",\"null\"],\"logicalType\":\"date" +
				"\"},{\"name\":\"PotentialEndDate\",\"type\":[\"int\",\"null\"],\"logicalType\":\"date\"},{\"name" +
				"\":\"Notices\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"Notices\",\"na" +
				"mespace\":\"MMH\",\"fields\":[{\"name\":\"Type\",\"type\":\"string\"},{\"name\":\"ServedDate\",\"t" +
				"ype\":\"int\",\"logicalType\":\"date\"},{\"name\":\"ExpiryDate\",\"type\":\"int\",\"logicalType\"" +
				":\"date\"},{\"name\":\"EffectiveDate\",\"type\":\"int\",\"logicalType\":\"date\"},{\"name\":\"End" +
				"Date\",\"type\":[\"int\",\"null\"],\"logicalType\":\"date\"}]}}},{\"name\":\"LegacyReferences\"" +
				",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"LegacyReferences\",\"name" +
				"space\":\"MMH\",\"fields\":[{\"name\":\"Name\",\"type\":\"string\"},{\"name\":\"Value\",\"type\":\"s" +
				"tring\"}]}}},{\"name\":\"IsMutualExchange\",\"type\":[\"boolean\",\"null\"]},{\"name\":\"Infor" +
				"mHousingBenefitsForChanges\",\"type\":[\"boolean\",\"null\"]},{\"name\":\"IsSublet\",\"type\"" +
				":[\"boolean\",\"null\"]},{\"name\":\"SubletEndDate\",\"type\":[\"int\",\"null\"],\"logicalType\"" +
				":\"date\"},{\"name\":\"VersionNumber\",\"type\":\"int\"}]}");
		private string _Id;
		private string _PaymentReference;
		private IList<MMH.HouseholdMember> _HouseholdMembers;
		private MMH.TenuredAsset _TenuredAsset;
		private MMH.Charges _Charges;
		private System.Nullable<int> _StartOfTenureDate;
		private System.Nullable<int> _EndOfTenureDate;
		private MMH.TenureType _TenureType;
		private System.Nullable<bool> _IsTenanted;
		private MMH.Terminated _Terminated;
		private System.Nullable<int> _SuccessionDate;
		private MMH.AgreementType _AgreementType;
		private System.Nullable<int> _EvictionDate;
		private System.Nullable<int> _PotentialEndDate;
		private IList<MMH.Notices> _Notices;
		private IList<MMH.LegacyReferences> _LegacyReferences;
		private System.Nullable<bool> _IsMutualExchange;
		private System.Nullable<bool> _InformHousingBenefitsForChanges;
		private System.Nullable<bool> _IsSublet;
		private System.Nullable<int> _SubletEndDate;
		private int _VersionNumber;
		public virtual Schema Schema
		{
			get
			{
				return TenureInformation._SCHEMA;
			}
		}
		public string Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				this._Id = value;
			}
		}
		public string PaymentReference
		{
			get
			{
				return this._PaymentReference;
			}
			set
			{
				this._PaymentReference = value;
			}
		}
		public IList<MMH.HouseholdMember> HouseholdMembers
		{
			get
			{
				return this._HouseholdMembers;
			}
			set
			{
				this._HouseholdMembers = value;
			}
		}
		public MMH.TenuredAsset TenuredAsset
		{
			get
			{
				return this._TenuredAsset;
			}
			set
			{
				this._TenuredAsset = value;
			}
		}
		public MMH.Charges Charges
		{
			get
			{
				return this._Charges;
			}
			set
			{
				this._Charges = value;
			}
		}
		public System.Nullable<int> StartOfTenureDate
		{
			get
			{
				return this._StartOfTenureDate;
			}
			set
			{
				this._StartOfTenureDate = value;
			}
		}
		public System.Nullable<int> EndOfTenureDate
		{
			get
			{
				return this._EndOfTenureDate;
			}
			set
			{
				this._EndOfTenureDate = value;
			}
		}
		public MMH.TenureType TenureType
		{
			get
			{
				return this._TenureType;
			}
			set
			{
				this._TenureType = value;
			}
		}
		public System.Nullable<bool> IsTenanted
		{
			get
			{
				return this._IsTenanted;
			}
			set
			{
				this._IsTenanted = value;
			}
		}
		public MMH.Terminated Terminated
		{
			get
			{
				return this._Terminated;
			}
			set
			{
				this._Terminated = value;
			}
		}
		public System.Nullable<int> SuccessionDate
		{
			get
			{
				return this._SuccessionDate;
			}
			set
			{
				this._SuccessionDate = value;
			}
		}
		public MMH.AgreementType AgreementType
		{
			get
			{
				return this._AgreementType;
			}
			set
			{
				this._AgreementType = value;
			}
		}
		public System.Nullable<int> EvictionDate
		{
			get
			{
				return this._EvictionDate;
			}
			set
			{
				this._EvictionDate = value;
			}
		}
		public System.Nullable<int> PotentialEndDate
		{
			get
			{
				return this._PotentialEndDate;
			}
			set
			{
				this._PotentialEndDate = value;
			}
		}
		public IList<MMH.Notices> Notices
		{
			get
			{
				return this._Notices;
			}
			set
			{
				this._Notices = value;
			}
		}
		public IList<MMH.LegacyReferences> LegacyReferences
		{
			get
			{
				return this._LegacyReferences;
			}
			set
			{
				this._LegacyReferences = value;
			}
		}
		public System.Nullable<bool> IsMutualExchange
		{
			get
			{
				return this._IsMutualExchange;
			}
			set
			{
				this._IsMutualExchange = value;
			}
		}
		public System.Nullable<bool> InformHousingBenefitsForChanges
		{
			get
			{
				return this._InformHousingBenefitsForChanges;
			}
			set
			{
				this._InformHousingBenefitsForChanges = value;
			}
		}
		public System.Nullable<bool> IsSublet
		{
			get
			{
				return this._IsSublet;
			}
			set
			{
				this._IsSublet = value;
			}
		}
		public System.Nullable<int> SubletEndDate
		{
			get
			{
				return this._SubletEndDate;
			}
			set
			{
				this._SubletEndDate = value;
			}
		}
		public int VersionNumber
		{
			get
			{
				return this._VersionNumber;
			}
			set
			{
				this._VersionNumber = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.Id;
			case 1: return this.PaymentReference;
			case 2: return this.HouseholdMembers;
			case 3: return this.TenuredAsset;
			case 4: return this.Charges;
			case 5: return this.StartOfTenureDate;
			case 6: return this.EndOfTenureDate;
			case 7: return this.TenureType;
			case 8: return this.IsTenanted;
			case 9: return this.Terminated;
			case 10: return this.SuccessionDate;
			case 11: return this.AgreementType;
			case 12: return this.EvictionDate;
			case 13: return this.PotentialEndDate;
			case 14: return this.Notices;
			case 15: return this.LegacyReferences;
			case 16: return this.IsMutualExchange;
			case 17: return this.InformHousingBenefitsForChanges;
			case 18: return this.IsSublet;
			case 19: return this.SubletEndDate;
			case 20: return this.VersionNumber;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.Id = (System.String)fieldValue; break;
			case 1: this.PaymentReference = (System.String)fieldValue; break;
			case 2: this.HouseholdMembers = (IList<MMH.HouseholdMember>)fieldValue; break;
			case 3: this.TenuredAsset = (MMH.TenuredAsset)fieldValue; break;
			case 4: this.Charges = (MMH.Charges)fieldValue; break;
			case 5: this.StartOfTenureDate = (System.Nullable<int>)fieldValue; break;
			case 6: this.EndOfTenureDate = (System.Nullable<int>)fieldValue; break;
			case 7: this.TenureType = (MMH.TenureType)fieldValue; break;
			case 8: this.IsTenanted = (System.Nullable<bool>)fieldValue; break;
			case 9: this.Terminated = (MMH.Terminated)fieldValue; break;
			case 10: this.SuccessionDate = (System.Nullable<int>)fieldValue; break;
			case 11: this.AgreementType = (MMH.AgreementType)fieldValue; break;
			case 12: this.EvictionDate = (System.Nullable<int>)fieldValue; break;
			case 13: this.PotentialEndDate = (System.Nullable<int>)fieldValue; break;
			case 14: this.Notices = (IList<MMH.Notices>)fieldValue; break;
			case 15: this.LegacyReferences = (IList<MMH.LegacyReferences>)fieldValue; break;
			case 16: this.IsMutualExchange = (System.Nullable<bool>)fieldValue; break;
			case 17: this.InformHousingBenefitsForChanges = (System.Nullable<bool>)fieldValue; break;
			case 18: this.IsSublet = (System.Nullable<bool>)fieldValue; break;
			case 19: this.SubletEndDate = (System.Nullable<int>)fieldValue; break;
			case 20: this.VersionNumber = (System.Int32)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
