// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MMH
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public partial class TenuredAsset : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse(@"{""type"":""record"",""name"":""TenuredAsset"",""namespace"":""MMH"",""fields"":[{""name"":""Id"",""type"":""string"",""logicalType"":""uuid""},{""name"":""TenuredAssetType"",""type"":[{""type"":""enum"",""name"":""TenuredAssetType"",""namespace"":""MMH"",""symbols"":[""Block"",""Concierge"",""Dwelling"",""LettableNonDwelling"",""MediumRiseBlock"",""NA"",""TravellerSite""]},""null""]},{""name"":""FullAddress"",""type"":""string""},{""name"":""Uprn"",""type"":""string""},{""name"":""PropertyReference"",""type"":""string""}]}");
		private string _Id;
		private System.Nullable<MMH.TenuredAssetType> _TenuredAssetType;
		private string _FullAddress;
		private string _Uprn;
		private string _PropertyReference;
		public virtual Schema Schema
		{
			get
			{
				return TenuredAsset._SCHEMA;
			}
		}
		public string Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				this._Id = value;
			}
		}
		public System.Nullable<MMH.TenuredAssetType> TenuredAssetType
		{
			get
			{
				return this._TenuredAssetType;
			}
			set
			{
				this._TenuredAssetType = value;
			}
		}
		public string FullAddress
		{
			get
			{
				return this._FullAddress;
			}
			set
			{
				this._FullAddress = value;
			}
		}
		public string Uprn
		{
			get
			{
				return this._Uprn;
			}
			set
			{
				this._Uprn = value;
			}
		}
		public string PropertyReference
		{
			get
			{
				return this._PropertyReference;
			}
			set
			{
				this._PropertyReference = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.Id;
			case 1: return this.TenuredAssetType;
			case 2: return this.FullAddress;
			case 3: return this.Uprn;
			case 4: return this.PropertyReference;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.Id = (System.String)fieldValue; break;
			case 1: this.TenuredAssetType = fieldValue == null ? (System.Nullable<MMH.TenuredAssetType>)null : (MMH.TenuredAssetType)fieldValue; break;
			case 2: this.FullAddress = (System.String)fieldValue; break;
			case 3: this.Uprn = (System.String)fieldValue; break;
			case 4: this.PropertyReference = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
